// Quebec Forest Fire Burn Viewer — Map logic

// 1. Initialize map, centered on Quebec
const map = L.map('map', { scrollWheelZoom: true }).setView([48.5, -71.5], 6);

// Single basemap (ESRI World Imagery)
const esriImagery = L.tileLayer(
  'https://server.arcgisonline.com/ArcGIS/rest/services/World_Imagery/MapServer/tile/{z}/{y}/{x}',
  {
    maxZoom: 19,
    attribution: 'Tiles &copy; Esri'
  }
).addTo(map);

// Simple burn-severity legend (static colors)
const legend = L.control({ position: "bottomright" });
legend.onAdd = function () {
  const div = L.DomUtil.create("div", "legend");
  const items = [
    // Match the magenta/orange burn palette used in the tiles
    { color: "#3c1b4a", label: "Low" },
    { color: "#8c2d7c", label: "Moderate" },
    { color: "#e24a8c", label: "High" },
    { color: "#ff9c33", label: "Very high" }
  ];
  div.innerHTML = '<div class="legend-title">Burn Severity</div>' +
    items.map(i => `
      <div class="legend-row">
        <span class="legend-swatch" style="background:${i.color}"></span>
        <span class="legend-label">${i.label}</span>
      </div>
    `).join("");
  return div;
};
legend.addTo(map);

// 2. PRE-GENERATED TILES
// For now, define them manually. Later you can generate this list from Python.
// bounds = [[lat_min, lon_min], [lat_max, lon_max]]

// Use tiles generated by Python snippet if loaded; otherwise empty.
const SNIPPET_TILES = (typeof PRESET_TILES !== "undefined") ? PRESET_TILES : [];
const PRESET_GROUPS = [];

// XYZ tiles from generated manifest (uses tileUrl to hit assets/xyz)
const XYZ_TILES = [
  {
    "id": "delta_nbr_p010r020_20220715_20230901_rgba",
    "label": "delta nbr p010r020 20220715 20230901 rgba",
    "tileUrl": "assets/xyz/delta_nbr_p010r020_20220715_20230901_rgba/{z}/{x}/{y}.png?v=10",
    "minZoom": 6,
    "maxZoom": 12,
    "bounds": [
      [
        56.22534693739668,
        -63.52601364921238
      ],
      [
        58.3501801030672,
        -59.47069859025995
      ]
    ]
  },
  {
    "id": "delta_nbr_p010r021_20220715_20230901_rgba",
    "label": "delta nbr p010r021 20220715 20230901 rgba",
    "tileUrl": "assets/xyz/delta_nbr_p010r021_20220715_20230901_rgba/{z}/{x}/{y}.png?v=10",
    "minZoom": 6,
    "maxZoom": 12,
    "bounds": [
      [
        54.81278223802434,
        -64.2590970982081
      ],
      [
        56.96759508837513,
        -60.387572859835494
      ]
    ]
  },
  {
    "id": "delta_nbr_p010r022_20220715_20230901_rgba",
    "label": "delta nbr p010r022 20220715 20230901 rgba",
    "tileUrl": "assets/xyz/delta_nbr_p010r022_20220715_20230901_rgba/{z}/{x}/{y}.png?v=10",
    "minZoom": 6,
    "maxZoom": 12,
    "bounds": [
      [
        53.39922118668972,
        -64.91190198155208
      ],
      [
        55.58020211129311,
        -61.208791892836395
      ]
    ]
  },
  {
    "id": "delta_nbr_p010r023_20220715_20240501_rgba",
    "label": "delta nbr p010r023 20220715 20240501 rgba",
    "tileUrl": "assets/xyz/delta_nbr_p010r023_20220715_20240501_rgba/{z}/{x}/{y}.png?v=10",
    "minZoom": 6,
    "maxZoom": 12,
    "bounds": [
      [
        51.98227234596541,
        -65.52816652375367
      ],
      [
        54.18708017466197,
        -61.982211242370695
      ]
    ]
  },
  {
    "id": "delta_nbr_p010r024_20220715_20230901_rgba",
    "label": "delta nbr p010r024 20220715 20230901 rgba",
    "tileUrl": "assets/xyz/delta_nbr_p010r024_20220715_20230901_rgba/{z}/{x}/{y}.png?v=10",
    "minZoom": 6,
    "maxZoom": 12,
    "bounds": [
      [
        50.56224692966095,
        -66.1165152006063
      ],
      [
        52.79147384861949,
        -62.70467060052346
      ]
    ]
  },
  {
    "id": "delta_nbr_p010r025_20220715_20230901_rgba",
    "label": "delta nbr p010r025 20220715 20230901 rgba",
    "tileUrl": "assets/xyz/delta_nbr_p010r025_20220715_20230901_rgba/{z}/{x}/{y}.png?v=10",
    "minZoom": 6,
    "maxZoom": 12,
    "bounds": [
      [
        49.14243066973027,
        -66.67239262808614
      ],
      [
        51.38862207840465,
        -63.390691915692926
      ]
    ]
  },
  {
    "id": "delta_nbr_p010r026_20220715_20230901_rgba",
    "label": "delta nbr p010r026 20220715 20230901 rgba",
    "tileUrl": "assets/xyz/delta_nbr_p010r026_20220715_20230901_rgba/{z}/{x}/{y}.png?v=10",
    "minZoom": 6,
    "maxZoom": 12,
    "bounds": [
      [
        47.72023847086569,
        -67.2073404730158
      ],
      [
        49.98170337473262,
        -64.0403300614986
      ]
    ]
  },
  {
    "id": "delta_nbr_p011r019_20220715_20230901_rgba",
    "label": "delta nbr p011r019 20220715 20230901 rgba",
    "tileUrl": "assets/xyz/delta_nbr_p011r019_20220715_20230901_rgba/{z}/{x}/{y}.png?v=10",
    "minZoom": 6,
    "maxZoom": 12,
    "bounds": [
      [
        57.596456422519715,
        -64.34874548167554
      ],
      [
        59.76575787467016,
        -60.12935907728205
      ]
    ]
  },
  {
    "id": "delta_nbr_p011r020_20220715_20230901_rgba",
    "label": "delta nbr p011r020 20220715 20230901 rgba",
    "tileUrl": "assets/xyz/delta_nbr_p011r020_20220715_20230901_rgba/{z}/{x}/{y}.png?v=10",
    "minZoom": 6,
    "maxZoom": 12,
    "bounds": [
      [
        56.19039020192783,
        -65.0629027426254
      ],
      [
        58.38935239979354,
        -61.048019564584266
      ]
    ]
  },
  {
    "id": "delta_nbr_p011r021_20230501_20240501_rgba",
    "label": "delta nbr p011r021 20230501 20240501 rgba",
    "tileUrl": "assets/xyz/delta_nbr_p011r021_20230501_20240501_rgba/{z}/{x}/{y}.png?v=10",
    "minZoom": 6,
    "maxZoom": 12,
    "bounds": [
      [
        54.77734031302711,
        -65.75079987889045
      ],
      [
        57.00369986721122,
        -61.921393162437624
      ]
    ]
  },
  {
    "id": "delta_nbr_p011r022_20220715_20230901_rgba",
    "label": "delta nbr p011r022 20220715 20230901 rgba",
    "tileUrl": "assets/xyz/delta_nbr_p011r022_20220715_20230901_rgba/{z}/{x}/{y}.png?v=10",
    "minZoom": 6,
    "maxZoom": 12,
    "bounds": [
      [
        53.364837931797844,
        -66.44369315034662
      ],
      [
        55.614661485608764,
        -62.78384387794209
      ]
    ]
  },
  {
    "id": "delta_nbr_p011r023_20220715_20230901_rgba",
    "label": "delta nbr p011r023 20220715 20230901 rgba",
    "tileUrl": "assets/xyz/delta_nbr_p011r023_20220715_20230901_rgba/{z}/{x}/{y}.png?v=10",
    "minZoom": 6,
    "maxZoom": 12,
    "bounds": [
      [
        51.94750700355661,
        -67.05889260703039
      ],
      [
        54.22247830195605,
        -63.55039006146745
      ]
    ]
  },
  {
    "id": "delta_nbr_p011r024_20220715_20230901_rgba",
    "label": "delta nbr p011r024 20220715 20230901 rgba",
    "tileUrl": "assets/xyz/delta_nbr_p011r024_20220715_20230901_rgba/{z}/{x}/{y}.png?v=10",
    "minZoom": 6,
    "maxZoom": 12,
    "bounds": [
      [
        50.664295281083106,
        -67.71260226711104
      ],
      [
        52.684681960232446,
        -64.22155931145633
      ]
    ]
  },
  {
    "id": "delta_nbr_p011r025_20220715_20230901_rgba",
    "label": "delta nbr p011r025 20220715 20230901 rgba",
    "tileUrl": "assets/xyz/delta_nbr_p011r025_20220715_20230901_rgba/{z}/{x}/{y}.png?v=10",
    "minZoom": 6,
    "maxZoom": 12,
    "bounds": [
      [
        49.23902973719202,
        -68.26935237703184
      ],
      [
        51.28800488229284,
        -64.90634959202072
      ]
    ]
  },
  {
    "id": "delta_nbr_p011r026_20220715_20230901_rgba",
    "label": "delta nbr p011r026 20220715 20230901 rgba",
    "tileUrl": "assets/xyz/delta_nbr_p011r026_20220715_20230901_rgba/{z}/{x}/{y}.png?v=10",
    "minZoom": 6,
    "maxZoom": 12,
    "bounds": [
      [
        47.81611885942686,
        -68.78646859160536
      ],
      [
        49.883341390346075,
        -65.53619935479658
      ]
    ]
  },
  {
    "id": "delta_nbr_p012r019_20230501_20240501_rgba",
    "label": "delta nbr p012r019 20230501 20240501 rgba",
    "tileUrl": "assets/xyz/delta_nbr_p012r019_20230501_20240501_rgba/{z}/{x}/{y}.png?v=10",
    "minZoom": 6,
    "maxZoom": 12,
    "bounds": [
      [
        57.56105897938296,
        -65.95246408613265
      ],
      [
        59.80495120799939,
        -61.784124464432175
      ]
    ]
  },
  {
    "id": "delta_nbr_p012r021_20230501_20240501_rgba",
    "label": "delta nbr p012r021 20230501 20240501 rgba",
    "tileUrl": "assets/xyz/delta_nbr_p012r021_20230501_20240501_rgba/{z}/{x}/{y}.png?v=10",
    "minZoom": 6,
    "maxZoom": 12,
    "bounds": [
      [
        54.74151107057056,
        -67.34309083013012
      ],
      [
        57.04212237126849,
        -63.56172803502379
      ]
    ]
  },
  {
    "id": "delta_nbr_p012r022_20220715_20240501_rgba",
    "label": "delta nbr p012r022 20220715 20240501 rgba",
    "tileUrl": "assets/xyz/delta_nbr_p012r022_20220715_20240501_rgba/{z}/{x}/{y}.png?v=10",
    "minZoom": 6,
    "maxZoom": 12,
    "bounds": [
      [
        53.467233557079,
        -68.03160045801192
      ],
      [
        55.51017876467993,
        -64.27448779678058
      ]
    ]
  },
  {
    "id": "delta_nbr_p012r023_20220715_20240501_rgba",
    "label": "delta nbr p012r023 20220715 20240501 rgba",
    "tileUrl": "assets/xyz/delta_nbr_p012r023_20220715_20240501_rgba/{z}/{x}/{y}.png?v=10",
    "minZoom": 6,
    "maxZoom": 12,
    "bounds": [
      [
        52.04936031552238,
        -68.65315303412541
      ],
      [
        54.1183073566043,
        -65.04551404607952
      ]
    ]
  },
  {
    "id": "delta_nbr_p012r024_20230501_20240501_rgba",
    "label": "delta nbr p012r024 20230501 20240501 rgba",
    "tileUrl": "assets/xyz/delta_nbr_p012r024_20230501_20240501_rgba/{z}/{x}/{y}.png?v=10",
    "minZoom": 6,
    "maxZoom": 12,
    "bounds": [
      [
        50.62793549134142,
        -69.26601440667855
      ],
      [
        52.721679629423214,
        -65.79980351542052
      ]
    ]
  },
  {
    "id": "delta_nbr_p012r025_20230501_20230901_rgba",
    "label": "delta nbr p012r025 20230501 20230901 rgba",
    "tileUrl": "assets/xyz/delta_nbr_p012r025_20230501_20230901_rgba/{z}/{x}/{y}.png?v=10",
    "minZoom": 6,
    "maxZoom": 12,
    "bounds": [
      [
        49.2060284049948,
        -69.82255628179546
      ],
      [
        51.321780317102984,
        -66.48393485500439
      ]
    ]
  },
  {
    "id": "delta_nbr_p012r026_20220715_20230901_rgba",
    "label": "delta nbr p012r026 20220715 20230901 rgba",
    "tileUrl": "assets/xyz/delta_nbr_p012r026_20220715_20230901_rgba/{z}/{x}/{y}.png?v=10",
    "minZoom": 6,
    "maxZoom": 12,
    "bounds": [
      [
        47.7789381718798,
        -70.32840790738148
      ],
      [
        49.919621344305675,
        -67.1052254782898
      ]
    ]
  },
  {
    "id": "delta_nbr_p013r019_20220715_20240501_rgba",
    "label": "delta nbr p013r019 20220715 20240501 rgba",
    "tileUrl": "assets/xyz/delta_nbr_p013r019_20220715_20240501_rgba/{z}/{x}/{y}.png?v=10",
    "minZoom": 6,
    "maxZoom": 12,
    "bounds": [
      [
        57.524831179833804,
        -67.38341642740698
      ],
      [
        59.84262736352362,
        -63.265603052494086
      ]
    ]
  },
  {
    "id": "delta_nbr_p013r020_20220715_20230901_rgba",
    "label": "delta nbr p013r020 20220715 20230901 rgba",
    "tileUrl": "assets/xyz/delta_nbr_p013r020_20220715_20230901_rgba/{z}/{x}/{y}.png?v=10",
    "minZoom": 6,
    "maxZoom": 12,
    "bounds": [
      [
        56.259010344083265,
        -68.2141156134322
      ],
      [
        58.316734680241716,
        -64.12566445508185
      ]
    ]
  },
  {
    "id": "delta_nbr_p013r021_20220715_20230901_rgba",
    "label": "delta nbr p013r021 20220715 20230901 rgba",
    "tileUrl": "assets/xyz/delta_nbr_p013r021_20220715_20230901_rgba/{z}/{x}/{y}.png?v=10",
    "minZoom": 6,
    "maxZoom": 12,
    "bounds": [
      [
        54.84621508663688,
        -68.88187740273528
      ],
      [
        56.93306389380905,
        -64.98408745272815
      ]
    ]
  },
  {
    "id": "delta_nbr_p013r022_20230501_20230901_rgba",
    "label": "delta nbr p013r022 20230501 20230901 rgba",
    "tileUrl": "assets/xyz/delta_nbr_p013r022_20230501_20230901_rgba/{z}/{x}/{y}.png?v=10",
    "minZoom": 6,
    "maxZoom": 12,
    "bounds": [
      [
        53.42918231852649,
        -69.60375386415002
      ],
      [
        55.548133677599886,
        -65.8784432878938
      ]
    ]
  },
  {
    "id": "delta_nbr_p013r023_20220715_20230901_rgba",
    "label": "delta nbr p013r023 20220715 20230901 rgba",
    "tileUrl": "assets/xyz/delta_nbr_p013r023_20220715_20230901_rgba/{z}/{x}/{y}.png?v=10",
    "minZoom": 6,
    "maxZoom": 12,
    "bounds": [
      [
        52.01164763434723,
        -70.17460529041357
      ],
      [
        54.15658373112919,
        -66.59538259125421
      ]
    ]
  },
  {
    "id": "delta_nbr_p013r024_20220715_20230901_rgba",
    "label": "delta nbr p013r024 20220715 20230901 rgba",
    "tileUrl": "assets/xyz/delta_nbr_p013r024_20220715_20230901_rgba/{z}/{x}/{y}.png?v=10",
    "minZoom": 6,
    "maxZoom": 12,
    "bounds": [
      [
        50.59332845992777,
        -70.76203257859859
      ],
      [
        52.75840180323456,
        -67.3222886854373
      ]
    ]
  },
  {
    "id": "delta_nbr_p013r025_20220715_20230901_rgba",
    "label": "delta nbr p013r025 20220715 20230901 rgba",
    "tileUrl": "assets/xyz/delta_nbr_p013r025_20220715_20230901_rgba/{z}/{x}/{y}.png?v=10",
    "minZoom": 6,
    "maxZoom": 12,
    "bounds": [
      [
        49.17215137459718,
        -71.32022775616471
      ],
      [
        51.35809249761407,
        -68.00735817040939
      ]
    ]
  },
  {
    "id": "delta_nbr_p013r026_20220715_20230901_rgba",
    "label": "delta nbr p013r026 20220715 20230901 rgba",
    "tileUrl": "assets/xyz/delta_nbr_p013r026_20220715_20230901_rgba/{z}/{x}/{y}.png?v=10",
    "minZoom": 6,
    "maxZoom": 12,
    "bounds": [
      [
        47.74846375427971,
        -71.85259892659295
      ],
      [
        49.953489633246946,
        -68.65965540911972
      ]
    ]
  },
  {
    "id": "delta_nbr_p013r027_20220715_20230901_rgba",
    "label": "delta nbr p013r027 20220715 20230901 rgba",
    "tileUrl": "assets/xyz/delta_nbr_p013r027_20220715_20230901_rgba/{z}/{x}/{y}.png?v=10",
    "minZoom": 6,
    "maxZoom": 12,
    "bounds": [
      [
        46.322469742943824,
        -72.36603656064261
      ],
      [
        48.547697543670786,
        -69.27892014960192
      ]
    ]
  },
  {
    "id": "delta_nbr_p013r028_20220715_20230901_rgba",
    "label": "delta nbr p013r028 20220715 20230901 rgba",
    "tileUrl": "assets/xyz/delta_nbr_p013r028_20220715_20230901_rgba/{z}/{x}/{y}.png?v=10",
    "minZoom": 6,
    "maxZoom": 12,
    "bounds": [
      [
        44.89724658879034,
        -72.85928600729389
      ],
      [
        47.1357423492741,
        -69.86882157181536
      ]
    ]
  },
  {
    "id": "delta_nbr_p013r029_20220715_20230901_rgba",
    "label": "delta nbr p013r029 20220715 20230901 rgba",
    "tileUrl": "assets/xyz/delta_nbr_p013r029_20220715_20230901_rgba/{z}/{x}/{y}.png?v=10",
    "minZoom": 6,
    "maxZoom": 12,
    "bounds": [
      [
        43.46995670738602,
        -73.34566682408725
      ],
      [
        45.720562883713036,
        -70.44414774377826
      ]
    ]
  },
  {
    "id": "delta_nbr_p014r019_20220715_20230901_rgba",
    "label": "delta nbr p014r019 20220715 20230901 rgba",
    "tileUrl": "assets/xyz/delta_nbr_p014r019_20220715_20230901_rgba/{z}/{x}/{y}.png?v=10",
    "minZoom": 6,
    "maxZoom": 12,
    "bounds": [
      [
        57.63060057711483,
        -68.99355289027068
      ],
      [
        59.73066735642926,
        -64.73854007896716
      ]
    ]
  },
  {
    "id": "delta_nbr_p014r020_20220715_20240501_rgba",
    "label": "delta nbr p014r020 20220715 20240501 rgba",
    "tileUrl": "assets/xyz/delta_nbr_p014r020_20220715_20240501_rgba/{z}/{x}/{y}.png?v=10",
    "minZoom": 6,
    "maxZoom": 12,
    "bounds": [
      [
        56.22150547330593,
        -69.74850882364345
      ],
      [
        58.353637262935564,
        -65.70120704346859
      ]
    ]
  },
  {
    "id": "delta_nbr_p014r021_20230501_20240501_rgba",
    "label": "delta nbr p014r021 20230501 20240501 rgba",
    "tileUrl": "assets/xyz/delta_nbr_p014r021_20230501_20240501_rgba/{z}/{x}/{y}.png?v=10",
    "minZoom": 6,
    "maxZoom": 12,
    "bounds": [
      [
        54.810478281707,
        -70.46442943749103
      ],
      [
        56.971938522069635,
        -66.60448099987802
      ]
    ]
  },
  {
    "id": "delta_nbr_p014r022_20230501_20230901_rgba",
    "label": "delta nbr p014r022 20230501 20230901 rgba",
    "tileUrl": "assets/xyz/delta_nbr_p014r022_20230501_20230901_rgba/{z}/{x}/{y}.png?v=10",
    "minZoom": 6,
    "maxZoom": 12,
    "bounds": [
      [
        53.39412786672984,
        -71.05606461221078
      ],
      [
        55.58502645792064,
        -67.36089450884204
      ]
    ]
  },
  {
    "id": "delta_nbr_p014r023_20220715_20230901_rgba",
    "label": "delta nbr p014r023 20220715 20230901 rgba",
    "tileUrl": "assets/xyz/delta_nbr_p014r023_20220715_20230901_rgba/{z}/{x}/{y}.png?v=10",
    "minZoom": 6,
    "maxZoom": 12,
    "bounds": [
      [
        51.978293462130374,
        -71.70706910161803
      ],
      [
        54.19115750376659,
        -68.16143195894198
      ]
    ]
  },
  {
    "id": "delta_nbr_p014r024_20220715_20230901_rgba",
    "label": "delta nbr p014r024 20220715 20230901 rgba",
    "tileUrl": "assets/xyz/delta_nbr_p014r024_20220715_20230901_rgba/{z}/{x}/{y}.png?v=10",
    "minZoom": 6,
    "maxZoom": 12,
    "bounds": [
      [
        50.56052500571543,
        -72.27739768391308
      ],
      [
        52.79176933253201,
        -68.86927723757267
      ]
    ]
  },
  {
    "id": "delta_nbr_p014r025_20220715_20230901_rgba",
    "label": "delta nbr p014r025 20220715 20230901 rgba",
    "tileUrl": "assets/xyz/delta_nbr_p014r025_20220715_20230901_rgba/{z}/{x}/{y}.png?v=10",
    "minZoom": 6,
    "maxZoom": 12,
    "bounds": [
      [
        49.139777373584266,
        -72.83677130129043
      ],
      [
        51.39063834941188,
        -69.55886518276657
      ]
    ]
  },
  {
    "id": "delta_nbr_p014r026_20220715_20230901_rgba",
    "label": "delta nbr p014r026 20220715 20230901 rgba",
    "tileUrl": "assets/xyz/delta_nbr_p014r026_20220715_20230901_rgba/{z}/{x}/{y}.png?v=10",
    "minZoom": 6,
    "maxZoom": 12,
    "bounds": [
      [
        47.716958424365984,
        -73.36711282767472
      ],
      [
        49.98821834370097,
        -70.20369099613917
      ]
    ]
  },
  {
    "id": "delta_nbr_p014r027_20220715_20230901_rgba",
    "label": "delta nbr p014r027 20220715 20230901 rgba",
    "tileUrl": "assets/xyz/delta_nbr_p014r027_20220715_20230901_rgba/{z}/{x}/{y}.png?v=10",
    "minZoom": 6,
    "maxZoom": 12,
    "bounds": [
      [
        46.41839794499626,
        -73.93703532822143
      ],
      [
        48.448820032546216,
        -70.77464490862309
      ]
    ]
  },
  {
    "id": "delta_nbr_p014r028_20220715_20230901_rgba",
    "label": "delta nbr p014r028 20220715 20230901 rgba",
    "tileUrl": "assets/xyz/delta_nbr_p014r028_20220715_20230901_rgba/{z}/{x}/{y}.png?v=10",
    "minZoom": 6,
    "maxZoom": 12,
    "bounds": [
      [
        44.985470363731906,
        -74.44713793981396
      ],
      [
        47.04145233763337,
        -71.38489472054168
      ]
    ]
  },
  {
    "id": "delta_nbr_p014r029_20220715_20230901_rgba",
    "label": "delta nbr p014r029 20220715 20230901 rgba",
    "tileUrl": "assets/xyz/delta_nbr_p014r029_20220715_20230901_rgba/{z}/{x}/{y}.png?v=10",
    "minZoom": 6,
    "maxZoom": 12,
    "bounds": [
      [
        43.55529139396413,
        -74.92094887913383
      ],
      [
        45.629560695509326,
        -71.9502859298027
      ]
    ]
  },
  {
    "id": "delta_nbr_p015r019_20220715_20230901_rgba",
    "label": "delta nbr p015r019 20220715 20230901 rgba",
    "tileUrl": "assets/xyz/delta_nbr_p015r019_20220715_20230901_rgba/{z}/{x}/{y}.png?v=10",
    "minZoom": 6,
    "maxZoom": 12,
    "bounds": [
      [
        57.594460081316754,
        -70.52435092286485
      ],
      [
        59.76959591841871,
        -66.3107424368701
      ]
    ]
  },
  {
    "id": "delta_nbr_p015r021_20220715_20240501_rgba",
    "label": "delta nbr p015r021 20220715 20240501 rgba",
    "tileUrl": "assets/xyz/delta_nbr_p015r021_20220715_20240501_rgba/{z}/{x}/{y}.png?v=10",
    "minZoom": 6,
    "maxZoom": 12,
    "bounds": [
      [
        54.77520900687928,
        -71.95594617269163
      ],
      [
        57.008044149963986,
        -68.13367884832331
      ]
    ]
  },
  {
    "id": "delta_nbr_p015r022_20220715_20240501_rgba",
    "label": "delta nbr p015r022 20220715 20240501 rgba",
    "tileUrl": "assets/xyz/delta_nbr_p015r022_20220715_20240501_rgba/{z}/{x}/{y}.png?v=10",
    "minZoom": 6,
    "maxZoom": 12,
    "bounds": [
      [
        53.35991260601995,
        -72.61017606262976
      ],
      [
        55.622930739930176,
        -68.95529878300052
      ]
    ]
  },
  {
    "id": "delta_nbr_p015r023_20220715_20230901_rgba",
    "label": "delta nbr p015r023 20220715 20230901 rgba",
    "tileUrl": "assets/xyz/delta_nbr_p015r023_20220715_20230901_rgba/{z}/{x}/{y}.png?v=10",
    "minZoom": 6,
    "maxZoom": 12,
    "bounds": [
      [
        51.94436806829439,
        -73.22456595832598
      ],
      [
        54.2269727243381,
        -69.72071828729088
      ]
    ]
  },
  {
    "id": "delta_nbr_p015r024_20220715_20240501_rgba",
    "label": "delta nbr p015r024 20220715 20240501 rgba",
    "tileUrl": "assets/xyz/delta_nbr_p015r024_20220715_20240501_rgba/{z}/{x}/{y}.png?v=10",
    "minZoom": 6,
    "maxZoom": 12,
    "bounds": [
      [
        50.657914032556704,
        -73.87830860017533
      ],
      [
        52.691180428152116,
        -70.3852250004981
      ]
    ]
  },
  {
    "id": "delta_nbr_p015r025_20220715_20230901_rgba",
    "label": "delta nbr p015r025 20220715 20230901 rgba",
    "tileUrl": "assets/xyz/delta_nbr_p015r025_20220715_20230901_rgba/{z}/{x}/{y}.png?v=10",
    "minZoom": 6,
    "maxZoom": 12,
    "bounds": [
      [
        49.234577957006906,
        -74.43837933751148
      ],
      [
        51.29105460751917,
        -71.0739584724096
      ]
    ]
  },
  {
    "id": "delta_nbr_p015r026_20220715_20230901_rgba",
    "label": "delta nbr p015r026 20220715 20230901 rgba",
    "tileUrl": "assets/xyz/delta_nbr_p015r026_20220715_20230901_rgba/{z}/{x}/{y}.png?v=10",
    "minZoom": 6,
    "maxZoom": 12,
    "bounds": [
      [
        47.81091525134761,
        -74.97081517578542
      ],
      [
        49.8888000219215,
        -71.72380131049442
      ]
    ]
  },
  {
    "id": "delta_nbr_p016r019_20230501_20230901_rgba",
    "label": "delta nbr p016r019 20230501 20230901 rgba",
    "tileUrl": "assets/xyz/delta_nbr_p016r019_20230501_20230901_rgba/{z}/{x}/{y}.png?v=10",
    "minZoom": 6,
    "maxZoom": 12,
    "bounds": [
      [
        57.5548875333262,
        -72.0974359652975
      ],
      [
        59.808942840977814,
        -67.93372913944259
      ]
    ]
  },
  {
    "id": "delta_nbr_p016r020_20230501_20240501_rgba",
    "label": "delta nbr p016r020 20230501 20240501 rgba",
    "tileUrl": "assets/xyz/delta_nbr_p016r020_20230501_20240501_rgba/{z}/{x}/{y}.png?v=10",
    "minZoom": 6,
    "maxZoom": 12,
    "bounds": [
      [
        56.1478019812502,
        -72.7563172182452
      ],
      [
        58.43099960353091,
        -68.79254154591719
      ]
    ]
  },
  {
    "id": "delta_nbr_p016r021_20220715_20240501_rgba",
    "label": "delta nbr p016r021 20220715 20240501 rgba",
    "tileUrl": "assets/xyz/delta_nbr_p016r021_20220715_20240501_rgba/{z}/{x}/{y}.png?v=10",
    "minZoom": 6,
    "maxZoom": 12,
    "bounds": [
      [
        54.73894533230025,
        -73.48740697301524
      ],
      [
        57.04675912906581,
        -69.71014118477153
      ]
    ]
  },
  {
    "id": "delta_nbr_p016r022_20220715_20230901_rgba",
    "label": "delta nbr p016r022 20220715 20230901 rgba",
    "tileUrl": "assets/xyz/delta_nbr_p016r022_20220715_20230901_rgba/{z}/{x}/{y}.png?v=10",
    "minZoom": 6,
    "maxZoom": 12,
    "bounds": [
      [
        53.46316897772651,
        -74.21244930428152
      ],
      [
        55.51449132494111,
        -70.45946894957127
      ]
    ]
  },
  {
    "id": "delta_nbr_p016r023_20220715_20230901_rgba",
    "label": "delta nbr p016r023 20220715 20230901 rgba",
    "tileUrl": "assets/xyz/delta_nbr_p016r023_20220715_20230901_rgba/{z}/{x}/{y}.png?v=10",
    "minZoom": 6,
    "maxZoom": 12,
    "bounds": [
      [
        52.04436334124006,
        -74.83691208027719
      ],
      [
        54.12164780295728,
        -71.23352298129514
      ]
    ]
  },
  {
    "id": "delta_nbr_p016r024_20220715_20230901_rgba",
    "label": "delta nbr p016r024 20220715 20230901 rgba",
    "tileUrl": "assets/xyz/delta_nbr_p016r024_20220715_20230901_rgba/{z}/{x}/{y}.png?v=10",
    "minZoom": 6,
    "maxZoom": 12,
    "bounds": [
      [
        50.62481917548731,
        -75.41019958869796
      ],
      [
        52.72554278398195,
        -71.94616890739263
      ]
    ]
  },
  {
    "id": "delta_nbr_p016r025_20220715_20230901_rgba",
    "label": "delta nbr p016r025 20220715 20230901 rgba",
    "tileUrl": "assets/xyz/delta_nbr_p016r025_20220715_20230901_rgba/{z}/{x}/{y}.png?v=10",
    "minZoom": 6,
    "maxZoom": 12,
    "bounds": [
      [
        49.202179228646244,
        -75.9707530064698
      ],
      [
        51.327527655554505,
        -72.63004444214413
      ]
    ]
  },
  {
    "id": "delta_nbr_p016r026_20220715_20230901_rgba",
    "label": "delta nbr p016r026 20220715 20230901 rgba",
    "tileUrl": "assets/xyz/delta_nbr_p016r026_20220715_20230901_rgba/{z}/{x}/{y}.png?v=10",
    "minZoom": 6,
    "maxZoom": 12,
    "bounds": [
      [
        47.77660592409788,
        -76.51656238716807
      ],
      [
        49.92254089448946,
        -73.29319585316954
      ]
    ]
  },
  {
    "id": "delta_nbr_p017r019_20220715_20240501_rgba",
    "label": "delta nbr p017r019 20220715 20240501 rgba",
    "tileUrl": "assets/xyz/delta_nbr_p017r019_20220715_20240501_rgba/{z}/{x}/{y}.png?v=10",
    "minZoom": 6,
    "maxZoom": 12,
    "bounds": [
      [
        57.518267129810674,
        -73.56817364144173
      ],
      [
        59.8474851587863,
        -69.45838309117426
      ]
    ]
  },
  {
    "id": "delta_nbr_p017r020_20220715_20240501_rgba",
    "label": "delta nbr p017r020 20220715 20240501 rgba",
    "tileUrl": "assets/xyz/delta_nbr_p017r020_20220715_20240501_rgba/{z}/{x}/{y}.png?v=10",
    "minZoom": 6,
    "maxZoom": 12,
    "bounds": [
      [
        56.25465135119551,
        -74.39820840216049
      ],
      [
        58.321118900852156,
        -70.3148439716844
      ]
    ]
  },
  {
    "id": "delta_nbr_p017r021_20220715_20230901_rgba",
    "label": "delta nbr p017r021 20220715 20230901 rgba",
    "tileUrl": "assets/xyz/delta_nbr_p017r021_20220715_20230901_rgba/{z}/{x}/{y}.png?v=10",
    "minZoom": 6,
    "maxZoom": 12,
    "bounds": [
      [
        54.84084198028874,
        -75.09677447017452
      ],
      [
        56.93983664447858,
        -71.2005048171465
      ]
    ]
  },
  {
    "id": "delta_nbr_p017r022_20220715_20240501_rgba",
    "label": "delta nbr p017r022 20220715 20240501 rgba",
    "tileUrl": "assets/xyz/delta_nbr_p017r022_20220715_20240501_rgba/{z}/{x}/{y}.png?v=10",
    "minZoom": 6,
    "maxZoom": 12,
    "bounds": [
      [
        53.425668280137444,
        -75.74817983457874
      ],
      [
        55.55168232930734,
        -72.02089283613948
      ]
    ]
  },
  {
    "id": "delta_nbr_p017r023_20220715_20230901_rgba",
    "label": "delta nbr p017r023 20220715 20230901 rgba",
    "tileUrl": "assets/xyz/delta_nbr_p017r023_20220715_20230901_rgba/{z}/{x}/{y}.png?v=10",
    "minZoom": 6,
    "maxZoom": 12,
    "bounds": [
      [
        52.00687680570333,
        -76.36679942804648
      ],
      [
        54.160365289584696,
        -72.79277130917428
      ]
    ]
  },
  {
    "id": "delta_nbr_p017r024_20220715_20230901_rgba",
    "label": "delta nbr p017r024 20220715 20230901 rgba",
    "tileUrl": "assets/xyz/delta_nbr_p017r024_20220715_20230901_rgba/{z}/{x}/{y}.png?v=10",
    "minZoom": 6,
    "maxZoom": 12,
    "bounds": [
      [
        50.58759177729629,
        -76.95254316522902
      ],
      [
        52.763702544425726,
        -73.5177293630746
      ]
    ]
  },
  {
    "id": "delta_nbr_p017r025_20220715_20230901_rgba",
    "label": "delta nbr p017r025 20220715 20230901 rgba",
    "tileUrl": "assets/xyz/delta_nbr_p017r025_20220715_20230901_rgba/{z}/{x}/{y}.png?v=10",
    "minZoom": 6,
    "maxZoom": 12,
    "bounds": [
      [
        49.168283150724434,
        -77.50526647029854
      ],
      [
        51.362242557392406,
        -74.19686936410416
      ]
    ]
  },
  {
    "id": "delta_nbr_p017r026_20230501_20230901_rgba",
    "label": "delta nbr p017r026 20230501 20230901 rgba",
    "tileUrl": "assets/xyz/delta_nbr_p017r026_20230501_20230901_rgba/{z}/{x}/{y}.png?v=10",
    "minZoom": 6,
    "maxZoom": 12,
    "bounds": [
      [
        47.74558700256367,
        -78.06857991895772
      ],
      [
        49.95662641225589,
        -74.88129347140925
      ]
    ]
  },
  {
    "id": "delta_nbr_p018r019_20220715_20230901_rgba",
    "label": "delta nbr p018r019 20220715 20230901 rgba",
    "tileUrl": "assets/xyz/delta_nbr_p018r019_20220715_20230901_rgba/{z}/{x}/{y}.png?v=10",
    "minZoom": 6,
    "maxZoom": 12,
    "bounds": [
      [
        57.62780560122138,
        -75.1593235618104
      ],
      [
        59.733236430120606,
        -70.90383321295879
      ]
    ]
  },
  {
    "id": "delta_nbr_p018r020_20220715_20230901_rgba",
    "label": "delta nbr p018r020 20220715 20230901 rgba",
    "tileUrl": "assets/xyz/delta_nbr_p018r020_20220715_20230901_rgba/{z}/{x}/{y}.png?v=10",
    "minZoom": 6,
    "maxZoom": 12,
    "bounds": [
      [
        56.217561735908696,
        -75.93226010424782
      ],
      [
        58.35825654723101,
        -71.8854655242611
      ]
    ]
  },
  {
    "id": "delta_nbr_p018r021_20220715_20230901_rgba",
    "label": "delta nbr p018r021 20220715 20230901 rgba",
    "tileUrl": "assets/xyz/delta_nbr_p018r021_20220715_20230901_rgba/{z}/{x}/{y}.png?v=10",
    "minZoom": 6,
    "maxZoom": 12,
    "bounds": [
      [
        54.805765203213106,
        -76.62296603375532
      ],
      [
        56.97486128625055,
        -72.76226944189244
      ]
    ]
  },
  {
    "id": "delta_nbr_p018r022_20220715_20230901_rgba",
    "label": "delta nbr p018r022 20220715 20230901 rgba",
    "tileUrl": "assets/xyz/delta_nbr_p018r022_20220715_20230901_rgba/{z}/{x}/{y}.png?v=10",
    "minZoom": 6,
    "maxZoom": 12,
    "bounds": [
      [
        53.39281253040514,
        -77.27710045164555
      ],
      [
        55.587812306338066,
        -73.58451023067215
      ]
    ]
  },
  {
    "id": "delta_nbr_p018r023_20220715_20230901_rgba",
    "label": "delta nbr p018r023 20220715 20230901 rgba",
    "tileUrl": "assets/xyz/delta_nbr_p018r023_20220715_20230901_rgba/{z}/{x}/{y}.png?v=10",
    "minZoom": 6,
    "maxZoom": 12,
    "bounds": [
      [
        51.97415001142566,
        -77.88156695845403
      ],
      [
        54.19496826758093,
        -74.34068961443693
      ]
    ]
  },
  {
    "id": "delta_nbr_p018r025_20220715_20230901_rgba",
    "label": "delta nbr p018r025 20220715 20230901 rgba",
    "tileUrl": "assets/xyz/delta_nbr_p018r025_20220715_20230901_rgba/{z}/{x}/{y}.png?v=10",
    "minZoom": 6,
    "maxZoom": 12,
    "bounds": [
      [
        49.13319776364093,
        -79.02961852078619
      ],
      [
        51.39761676340403,
        -75.75731974547782
      ]
    ]
  },
  {
    "id": "delta_nbr_p018r026_20220715_20230901_rgba",
    "label": "delta nbr p018r026 20220715 20230901 rgba",
    "tileUrl": "assets/xyz/delta_nbr_p018r026_20220715_20230901_rgba/{z}/{x}/{y}.png?v=10",
    "minZoom": 6,
    "maxZoom": 12,
    "bounds": [
      [
        47.84045756031215,
        -79.62364607979602
      ],
      [
        49.858215181491566,
        -76.35632063920403
      ]
    ]
  },
  {
    "id": "delta_nbr_p019r019_20220715_20230901_rgba",
    "label": "delta nbr p019r019 20220715 20230901 rgba",
    "tileUrl": "assets/xyz/delta_nbr_p019r019_20220715_20230901_rgba/{z}/{x}/{y}.png?v=10",
    "minZoom": 6,
    "maxZoom": 12,
    "bounds": [
      [
        57.58939086396745,
        -76.70983780748337
      ],
      [
        59.7760783921616,
        -72.50264558331297
      ]
    ]
  },
  {
    "id": "delta_nbr_p019r020_20220715_20230901_rgba",
    "label": "delta nbr p019r020 20220715 20230901 rgba",
    "tileUrl": "assets/xyz/delta_nbr_p019r020_20220715_20230901_rgba/{z}/{x}/{y}.png?v=10",
    "minZoom": 6,
    "maxZoom": 12,
    "bounds": [
      [
        56.18074001828265,
        -77.44428487039013
      ],
      [
        58.39745577677746,
        -73.44284592503286
      ]
    ]
  },
  {
    "id": "delta_nbr_p019r021_20220715_20230901_rgba",
    "label": "delta nbr p019r021 20220715 20230901 rgba",
    "tileUrl": "assets/xyz/delta_nbr_p019r021_20220715_20230901_rgba/{z}/{x}/{y}.png?v=10",
    "minZoom": 6,
    "maxZoom": 12,
    "bounds": [
      [
        54.76795187790966,
        -78.13735718272585
      ],
      [
        57.014591921318946,
        -74.32126794856754
      ]
    ]
  },
  {
    "id": "delta_nbr_p019r022_20220715_20230901_rgba",
    "label": "delta nbr p019r022 20220715 20230901 rgba",
    "tileUrl": "assets/xyz/delta_nbr_p019r022_20220715_20230901_rgba/{z}/{x}/{y}.png?v=10",
    "minZoom": 6,
    "maxZoom": 12,
    "bounds": [
      [
        53.354327169895505,
        -78.7901010689657
      ],
      [
        55.6255533953623,
        -75.14110016449277
      ]
    ]
  },
  {
    "id": "delta_nbr_p019r023_20220715_20230901_rgba",
    "label": "delta nbr p019r023 20220715 20230901 rgba",
    "tileUrl": "assets/xyz/delta_nbr_p019r023_20220715_20230901_rgba/{z}/{x}/{y}.png?v=10",
    "minZoom": 6,
    "maxZoom": 12,
    "bounds": [
      [
        51.9401812304733,
        -79.41195836653291
      ],
      [
        54.23108876546754,
        -75.90948697865701
      ]
    ]
  },
  {
    "id": "delta_nbr_p019r024_20220715_20230901_rgba",
    "label": "delta nbr p019r024 20220715 20230901 rgba",
    "tileUrl": "assets/xyz/delta_nbr_p019r024_20220715_20230901_rgba/{z}/{x}/{y}.png?v=10",
    "minZoom": 6,
    "maxZoom": 12,
    "bounds": [
      [
        50.65413245645015,
        -80.0608913824828
      ],
      [
        52.69290598006471,
        -76.57162759498988
      ]
    ]
  },
  {
    "id": "delta_nbr_p019r025_20220715_20230901_rgba",
    "label": "delta nbr p019r025 20220715 20230901 rgba",
    "tileUrl": "assets/xyz/delta_nbr_p019r025_20220715_20230901_rgba/{z}/{x}/{y}.png?v=10",
    "minZoom": 6,
    "maxZoom": 12,
    "bounds": [
      [
        49.232618650353864,
        -80.61971790617903
      ],
      [
        51.294415100146125,
        -77.25877546140906
      ]
    ]
  },
  {
    "id": "delta_nbr_p019r026_20220715_20230901_rgba",
    "label": "delta nbr p019r026 20220715 20230901 rgba",
    "tileUrl": "assets/xyz/delta_nbr_p019r026_20220715_20230901_rgba/{z}/{x}/{y}.png?v=10",
    "minZoom": 6,
    "maxZoom": 12,
    "bounds": [
      [
        47.808114893771766,
        -81.15513205938171
      ],
      [
        49.89114985239974,
        -77.90746064177144
      ]
    ]
  },
  {
    "id": "delta_nbr_p020r019_20220715_20240501_rgba",
    "label": "delta nbr p020r019 20220715 20240501 rgba",
    "tileUrl": "assets/xyz/delta_nbr_p020r019_20220715_20240501_rgba/{z}/{x}/{y}.png?v=10",
    "minZoom": 6,
    "maxZoom": 12,
    "bounds": [
      [
        57.551625592383346,
        -78.2275772176776
      ],
      [
        59.81534519326539,
        -74.06725261427286
      ]
    ]
  },
  {
    "id": "delta_nbr_p020r020_20220715_20230901_rgba",
    "label": "delta nbr p020r020 20220715 20230901 rgba",
    "tileUrl": "assets/xyz/delta_nbr_p020r020_20220715_20230901_rgba/{z}/{x}/{y}.png?v=10",
    "minZoom": 6,
    "maxZoom": 12,
    "bounds": [
      [
        56.146390712034716,
        -78.97364716928188
      ],
      [
        58.43386052920719,
        -75.01858113595695
      ]
    ]
  },
  {
    "id": "delta_nbr_p020r021_20220715_20230901_rgba",
    "label": "delta nbr p020r021 20220715 20230901 rgba",
    "tileUrl": "assets/xyz/delta_nbr_p020r021_20220715_20230901_rgba/{z}/{x}/{y}.png?v=10",
    "minZoom": 6,
    "maxZoom": 12,
    "bounds": [
      [
        54.73478014291328,
        -79.66884560556676
      ],
      [
        57.05094257360551,
        -75.89814633438299
      ]
    ]
  },
  {
    "id": "delta_nbr_p020r022_20220715_20230901_rgba",
    "label": "delta nbr p020r022 20220715 20230901 rgba",
    "tileUrl": "assets/xyz/delta_nbr_p020r022_20220715_20230901_rgba/{z}/{x}/{y}.png?v=10",
    "minZoom": 6,
    "maxZoom": 12,
    "bounds": [
      [
        53.45885344915063,
        -80.39778326644048
      ],
      [
        55.5185245956752,
        -76.6445044810046
      ]
    ]
  },
  {
    "id": "delta_nbr_p020r023_20220715_20230901_rgba",
    "label": "delta nbr p020r023 20220715 20230901 rgba",
    "tileUrl": "assets/xyz/delta_nbr_p020r023_20220715_20230901_rgba/{z}/{x}/{y}.png?v=10",
    "minZoom": 6,
    "maxZoom": 12,
    "bounds": [
      [
        52.03908053373851,
        -81.0162558368594
      ],
      [
        54.1271125300728,
        -77.41217918763276
      ]
    ]
  },
  {
    "id": "delta_nbr_p020r024_20220715_20230901_rgba",
    "label": "delta nbr p020r024 20220715 20230901 rgba",
    "tileUrl": "assets/xyz/delta_nbr_p020r024_20220715_20230901_rgba/{z}/{x}/{y}.png?v=10",
    "minZoom": 6,
    "maxZoom": 12,
    "bounds": [
      [
        50.61859544357121,
        -81.60097766484239
      ],
      [
        52.73030575543528,
        -78.13693613400893
      ]
    ]
  },
  {
    "id": "delta_nbr_p020r025_20220715_20230901_rgba",
    "label": "delta nbr p020r025 20220715 20230901 rgba",
    "tileUrl": "assets/xyz/delta_nbr_p020r025_20220715_20230901_rgba/{z}/{x}/{y}.png?v=10",
    "minZoom": 6,
    "maxZoom": 12,
    "bounds": [
      [
        49.19503578382175,
        -82.16003136187945
      ],
      [
        51.33128684658908,
        -78.82365808979921
      ]
    ]
  },
  {
    "id": "delta_nbr_p020r026_20220715_20230901_rgba",
    "label": "delta nbr p020r026 20220715 20230901 rgba",
    "tileUrl": "assets/xyz/delta_nbr_p020r026_20220715_20230901_rgba/{z}/{x}/{y}.png?v=10",
    "minZoom": 6,
    "maxZoom": 12,
    "bounds": [
      [
        47.77431963811654,
        -82.68067655418598
      ],
      [
        49.92757762966668,
        -79.46021927105316
      ]
    ]
  }
];

PRESET_GROUPS.push({
  name: "XYZ tiles",
  tiles: XYZ_TILES
});

// Overlay opacity for pre-generated rasters
const PRESET_OVERLAY_OPACITY = 0.75;
const PRESET_TILE_DEFAULT_ZOOM = { min: 5, max: 13 };

// Keep track of overlay layers + rectangles
const presetGroups = [];
const presetRects = [];
let rectOutlinesOn = false;

// WRS grid (clipped to Quebec) — expects GeoJSON at this path
const WRS_GRID_URL = 'assets/QcGridGJ.geojson';
const wrsGridGroup = L.layerGroup();       // togglable layer for the grid
const wrsSelection = L.geoJSON(null, {     // highlight of the chosen tile
  style: { color: '#00c2ff', weight: 2, fillOpacity: 0 }
}).addTo(wrsGridGroup);
let wrsFeatures = [];
let lastFeatureClick = 0;
// Keep track of latest API result overlays so we can replace them
let latestApiLayers = [];
const MAX_SELECTED_TILES = 5;

let boundsUnion = null;

function extendBounds(union, b) {
  if (!union) return L.latLngBounds(b);
  return union.extend(b);
}

function createPresetLayer(tile, bounds) {
  if (tile.tileUrl) {
    const minZoom = tile.minZoom ?? PRESET_TILE_DEFAULT_ZOOM.min;
    const maxZoom = tile.maxZoom ?? PRESET_TILE_DEFAULT_ZOOM.max;
    return L.tileLayer(tile.tileUrl, {
      opacity: PRESET_OVERLAY_OPACITY,
      bounds,
      minZoom,
      maxZoom,
      maxNativeZoom: maxZoom,
      tms: !!tile.tms,
      crossOrigin: true
    });
  }

  if (!tile.url) {
    console.warn("Tile is missing a url/tileUrl", tile);
    return null;
  }

  return L.imageOverlay(tile.url, bounds, { opacity: PRESET_OVERLAY_OPACITY });
}

function buildPresetTiles() {
  boundsUnion = null;
  PRESET_GROUPS.forEach(group => {
    const grpLayer = L.layerGroup();
    group.tiles.forEach(tile => {
      const bounds = L.latLngBounds(tile.bounds);
      const layer = createPresetLayer(tile, bounds);
      if (!layer) return;

      const rect = L.rectangle(bounds, {
        color: '#ffd166',
        weight: 1,
        fillOpacity: 0
      });

      rect.on('click', () => {
        showTileInfo(tile);
        highlightRect(rect);
      });

      layer.addTo(grpLayer);
      rect.addTo(grpLayer);
      presetRects.push(rect);
      boundsUnion = extendBounds(boundsUnion, bounds);
    });
    presetGroups.push({ name: group.name, layer: grpLayer });
  });

  if (boundsUnion) {
    map.fitBounds(boundsUnion.pad(0.1));
  }
}

buildPresetTiles();

// Sidebar group toggles
const chkGrid = document.getElementById("chkGrid");
const chkXYZ = document.getElementById("chkXYZ");

// Initial visibility (only XYZ tiles)
setGroupVisibility("XYZ tiles", true);
if (chkGrid && chkGrid.checked) {
  wrsGridGroup.addTo(map);
} else {
  map.removeLayer(wrsGridGroup);
}

function setGroupVisibility(name, visible) {
  const grp = presetGroups.find(g => g.name === name);
  if (!grp) return;
  if (visible) {
    grp.layer.addTo(map);
  } else {
    map.removeLayer(grp.layer);
  }
}
function setRectVisibility(show) {
  rectOutlinesOn = show;
  presetRects.forEach(r => {
    r.setStyle({
      opacity: show ? 1 : 0,
      weight: show ? 1 : 0,
      fillOpacity: 0
    });
  });
}
if (chkXYZ) {
  chkXYZ.addEventListener("change", e => {
    setGroupVisibility("XYZ tiles", e.target.checked);
  });
}
if (chkGrid) {
  chkGrid.addEventListener("change", e => {
    if (e.target.checked) {
      wrsGridGroup.addTo(map);
    } else {
      map.removeLayer(wrsGridGroup);
    }
  });
}
const chkOutlines = document.getElementById("chkOutlines");
if (chkOutlines) {
  setRectVisibility(chkOutlines.checked);
  chkOutlines.addEventListener("change", e => setRectVisibility(e.target.checked));
} else {
  setRectVisibility(false);
}

// 5. Tile info UI

const tileInfoDiv = document.getElementById('tileInfo');
let lastHighlighted = null;

function showTileInfo(tile) {
  if (!tileInfoDiv) return;

  const percentText =
    tile.percentChanged == null || !Number.isFinite(tile.percentChanged)
      ? 'Percent changed: (not calculated yet)'
      : `Percent changed: ${tile.percentChanged.toFixed(1)}%`;

  tileInfoDiv.innerHTML = `
    <p><strong>${tile.label}</strong></p>
    <p>Tile ID: <code>${tile.id}</code></p>
    <p>Pre-fire date: ${tile.preDate}</p>
    <p>Post-fire date: ${tile.postDate}</p>
    <p>${percentText}</p>
    <p class="muted">In the future, clicking here could trigger a live API run for this tile + custom dates.</p>
  `;
}

function highlightRect(rect) {
  if (lastHighlighted) {
    lastHighlighted.setStyle({ weight: 1, color: '#ffd166' });
  }
  rect.setStyle({ weight: 3, color: '#ffffff' });
  lastHighlighted = rect;
}

// --- WRS grid loading + selection ---

function propsPath(f) {
  const p = f && f.properties ? f.properties : {};
  return p.PATH || p.path || p.Path || p.wrs_path || p.WRS_PATH || null;
}

function propsRow(f) {
  const p = f && f.properties ? f.properties : {};
  return p.ROW || p.row || p.Row || p.wrs_row || p.WRS_ROW || null;
}

function featureKey(f) {
  const p = propsPath(f);
  const r = propsRow(f);
  return p != null && r != null ? `${p}-${r}` : null;
}

const selectedFeatures = new Map();
// removed per-tile date choices and popup

function baseWrsStyle() {
  return { color: '#ffd166', weight: 0.6, fillOpacity: 0, opacity: 0.7 };
}

fetch(WRS_GRID_URL)
  .then(r => {
    if (!r.ok) throw new Error(`HTTP ${r.status}`);
    return r.json();
  })
  .then(data => {
    wrsFeatures = (data && data.features) || [];
    L.geoJSON(data, {
      style: baseWrsStyle,
      onEachFeature: (feature, layer) => {
        layer.on('mouseover', () => {
          layer.setStyle({ color: '#ffffff', weight: 2, fillOpacity: 0, opacity: 1 });
          if (layer.bringToFront) layer.bringToFront();
        });
        layer.on('mouseout', () => {
          layer.setStyle(baseWrsStyle());
        });
        layer.on('click', (e) => {
          lastFeatureClick = Date.now();
          const isShift = e.originalEvent && e.originalEvent.shiftKey;
          if (isShift) {
            toggleFeature(feature);
          } else {
            setSelection([feature]);
          }
          if (L.DomEvent && L.DomEvent.stopPropagation) {
            L.DomEvent.stopPropagation(e);
          }
        });
      }
    }).addTo(wrsGridGroup);
    console.log(`Loaded WRS grid with ${wrsFeatures.length} features`);
  })
  .catch(err => {
    console.warn("Could not load WRS grid", err);
  });

function highlightWrsSelection(feature) {
  wrsSelection.clearLayers();
  if (feature) {
    wrsSelection.addData(feature);
  }
}

function applyWrsSelection(feature) {
  const path = propsPath(feature);
  const row = propsRow(feature);

  const pathInput = document.getElementById("apiPath");
  const rowInput = document.getElementById("apiRow");
  if (pathInput && path != null) pathInput.value = path;
  if (rowInput && row != null) rowInput.value = row;

  if (tileInfoDiv && path != null && row != null) {
    tileInfoDiv.innerHTML = `
      <p><strong>Selected path/row:</strong> ${String(path).padStart(3, "0")}/${String(row).padStart(3, "0")}</p>
      <p class="muted">Click “Run analysis” to fetch delta NBR for these dates.</p>
    `;
  }

  updateSelectedList();
}

function setSelection(features) {
  selectedFeatures.clear();
  (features || []).forEach(f => {
    const key = featureKey(f);
    if (key) selectedFeatures.set(key, f);
  });
  updateSelectionLayer();
  updateSelectedList();

  // If single selection, fill form
  if (selectedFeatures.size === 1) {
    const only = [...selectedFeatures.values()][0];
    applyWrsSelection(only);
  } else if (tileInfoDiv && selectedFeatures.size > 1) {
    const list = [...selectedFeatures.values()].map(f => {
      const p = String(propsPath(f) || "").padStart(3, "0");
      const r = String(propsRow(f) || "").padStart(3, "0");
      return `${p}/${r}`;
    }).join(", ");
    tileInfoDiv.innerHTML = `
      <p><strong>Selected tiles:</strong> ${list}</p>
      <p class="muted">Shift-click to add/remove tiles. Dates come from the form.</p>
    `;
  }
}

function toggleFeature(feature) {
  const key = featureKey(feature);
  if (!key) return;
  if (!selectedFeatures.has(key) && selectedFeatures.size >= MAX_SELECTED_TILES) {
    alert(`You can select up to ${MAX_SELECTED_TILES} tiles at once.`);
    return;
  }
  if (selectedFeatures.has(key)) {
    selectedFeatures.delete(key);
  } else {
    selectedFeatures.set(key, feature);
  }
  updateSelectionLayer();
  updateSelectedList();

  if (selectedFeatures.size === 1) {
    applyWrsSelection(selectedFeatures.values().next().value);
  } else if (tileInfoDiv) {
    const list = [...selectedFeatures.values()].map(f => {
      const p = String(propsPath(f) || "").padStart(3, "0");
      const r = String(propsRow(f) || "").padStart(3, "0");
      return `${p}/${r}`;
    }).join(", ");
    tileInfoDiv.innerHTML = `
      <p><strong>Selected tiles:</strong> ${list}</p>
      <p class="muted">Shift-click to add/remove tiles. Dates come from the form.</p>
    `;
  }
}

function updateSelectionLayer() {
  wrsSelection.clearLayers();
  selectedFeatures.forEach(f => wrsSelection.addData(f));
}

function updateSelectedList() {
  const box = document.getElementById("selectedList");
  if (!box) return;
  if (selectedFeatures.size === 0) {
    box.innerHTML = "<p><strong>Selected tiles:</strong> (none)</p>";
    return;
  }
  const list = [...selectedFeatures.values()].map(f => {
    const p = String(propsPath(f) || "").padStart(3, "0");
    const r = String(propsRow(f) || "").padStart(3, "0");
    return `${p}/${r}`;
  }).join(", ");
  box.innerHTML = `<p><strong>Selected tiles:</strong> ${list}</p>`;
}


// Also allow map clicks: pick the containing feature whose centroid is closest
map.on('click', e => {
  if (Date.now() - lastFeatureClick < 50) return;
  if (!wrsFeatures.length || typeof turf === "undefined") return;

  const pt = turf.point([e.latlng.lng, e.latlng.lat]);
  const hits = wrsFeatures.filter(f => turf.booleanPointInPolygon(pt, f));
  if (!hits.length) return;

  const chosen = hits.slice().sort((a, b) => {
    const da = turf.distance(pt, turf.centroid(a));
    const db = turf.distance(pt, turf.centroid(b));
    return da - db;
  })[0];

  setSelection([chosen]);
});

// --- Custom analysis (API) wiring ---

// --- Custom analysis (API) wiring ---

const runApiBtn   = document.getElementById("runApiBtn");
const apiResultEl = document.getElementById("apiResult");
const loadingOverlay = document.getElementById("loadingOverlay");

// Clear date fields and disable browser autocomplete
["preStart","preEnd","postStart","postEnd"].forEach(id => {
  const el = document.getElementById(id);
  if (el) {
    el.value = "";
    el.setAttribute("autocomplete", "off");
  }
});

function clearApiOverlays() {
  latestApiLayers.forEach(layer => {
    map.removeLayer(layer);
  });
  latestApiLayers = [];
}

if (runApiBtn && apiResultEl) {
  runApiBtn.addEventListener("click", async () => {
    const path      = parseInt(document.getElementById("apiPath").value, 10);
    const row       = parseInt(document.getElementById("apiRow").value, 10);
    const preStart  = document.getElementById("preStart").value;
    const preEnd    = document.getElementById("preEnd").value;
    const postStart = document.getElementById("postStart").value;
    const postEnd   = document.getElementById("postEnd").value;

    if (!preStart || !preEnd || !postStart || !postEnd) {
      apiResultEl.textContent = "Please fill all date fields.";
      return;
    }

    apiResultEl.textContent = "Running analysis...";

    try {
      clearApiOverlays();
      if (loadingOverlay) loadingOverlay.classList.remove("hidden");

      // Build payload: batch if multiple selections, else single
      const requests = [];
      if (selectedFeatures.size > 0) {
        selectedFeatures.forEach(f => {
          const p = propsPath(f);
          const r = propsRow(f);
          if (p != null && r != null) {
            requests.push({
              path: p,
              row: r,
              pre_start: preStart,
              pre_end: preEnd,
              post_start: postStart,
              post_end: postEnd
            });
          }
        });
      } else {
        requests.push({
          path,
          row,
          pre_start: preStart,
          pre_end: preEnd,
          post_start: postStart,
          post_end: postEnd
        });
      }

      if (requests.length === 0) {
        apiResultEl.textContent = "Please select tiles or enter path/row.";
        return;
      }

      // If multiple requests, use batch endpoint
      if (requests.length > 1) {
        const batchResp = await fetch("/api/run_dnbr_batch", {
          method: "POST",
          headers: { "Content-Type": "application/json" },
          body: JSON.stringify({ requests })
        });

        if (!batchResp.ok) {
          const text = await batchResp.text();
          throw new Error(`HTTP ${batchResp.status}: ${text}`);
        }

        const data = await batchResp.json();
        if (data.error) {
          apiResultEl.textContent = "Error: " + data.error;
          return;
        }

        const errors = data.errors || [];
        const results = data.results || [];

        const rows = [];
        results.forEach(res => {
          const s = res.stats || {};
          const percent =
            s.percent_changed != null
              ? s.percent_changed.toFixed(1) + "%"
              : "?";

          rows.push(`<p><strong>P${String(res.path).padStart(3, "0")}R${String(res.row).padStart(3, "0")}:</strong> valid ${s.valid_pixels ?? "?"}, changed ${s.changed_pixels ?? "?"}, % ${percent}</p>`);

          if (res.png_url && res.bounds) {
            const b = res.bounds;
            if (
              b.min_lat != null && b.min_lon != null &&
              b.max_lat != null && b.max_lon != null
            ) {
              const apiBounds = [
                [b.min_lat, b.min_lon],
                [b.max_lat, b.max_lon]
              ];
          const label = `Custom P${String(res.path).padStart(3, "0")}R${String(res.row).padStart(3, "0")} (${preStart} → ${postStart})`;

              const layer = L.imageOverlay(res.png_url, apiBounds, { opacity: 0.75 });
              layer.addTo(map);
              latestApiLayers.push(layer);
            }
          }
        });

        errors.forEach(err => {
          rows.push(`<p class="muted">Error P${String(err.path || "?").padStart(3, "0")}R${String(err.row || "?").padStart(3, "0")}: ${err.error}</p>`);
        });

        apiResultEl.innerHTML = rows.join("") || "No results.";
      } else {
        const resp = await fetch("/api/run_dnbr", {
          method: "POST",
          headers: { "Content-Type": "application/json" },
          body: JSON.stringify({
            path: requests[0].path,
            row: requests[0].row,
            pre_start: preStart,
            pre_end: preEnd,
            post_start: postStart,
            post_end: postEnd
          })
        });

        if (!resp.ok) {
          const text = await resp.text();
          throw new Error(`HTTP ${resp.status}: ${text}`);
        }

        const data = await resp.json();

        if (data.error) {
          apiResultEl.textContent = "Error: " + data.error;
          return;
        }

        const s = data.stats || {};
        const percent =
          s.percent_changed != null
            ? s.percent_changed.toFixed(1) + "%"
            : "?";

        if (data.png_url && data.bounds) {
          const b = data.bounds;
          if (
            b.min_lat != null && b.min_lon != null &&
            b.max_lat != null && b.max_lon != null
          ) {
            const apiBounds = [
              [b.min_lat, b.min_lon],
              [b.max_lat, b.max_lon]
            ];
            const pathVal = document.getElementById("apiPath").value;
            const rowVal = document.getElementById("apiRow").value;
            const label = `Custom P${pathVal}R${rowVal} (${preStart} → ${postStart})`;

            const layer = L.imageOverlay(data.png_url, apiBounds, { opacity: 0.75 });
            layer.addTo(map);
            latestApiLayers.push(layer);
          }
        }

        apiResultEl.innerHTML = `
          <p><strong>Valid pixels:</strong> ${s.valid_pixels ?? "?"}</p>
          <p><strong>Changed pixels:</strong> ${s.changed_pixels ?? "?"}</p>
          <p><strong>% burned:</strong> ${percent}</p>
        `;
      }
    } catch (err) {
      apiResultEl.textContent = "Request failed: " + err.message;
      console.error(err);
    } finally {
      if (loadingOverlay) loadingOverlay.classList.add("hidden");
    }
  });
}
